" ####################################   VUNDLE   #######################################

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle
Plugin 'VundleVim/Vundle.vim'

" Theme
Plugin 'tomasiser/vim-code-dark'

" Whitespace management
Plugin 'ntpeters/vim-better-whitespace'

" Commenting
Plugin 'scrooloose/nerdcommenter'

" Tree-style file explorer
Plugin 'scrooloose/nerdtree'

" Status/tabline
Plugin 'itchyny/lightline.vim'

" Git
Plugin 'tpope/vim-fugitive'

" Buffers
Plugin 'Asheq/close-buffers.vim'

" Sessions
Plugin 'tpope/vim-obsession'
Plugin 'dhruvasagar/vim-prosession'

" Vim-tmux
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'tmux-plugins/vim-tmux-focus-events'

" Fuzzy finder
Plugin 'junegunn/fzf.vim'

call vundle#end()

" ####################################   GENERAL SETTINGS   #######################################

let mapleader = ","
let maplocalleader = ",,"

filetype plugin indent on
set history=500
set omnifunc=syntaxcomplete#Complete
set autoread
set wildmenu
set ruler
set cmdheight=2
set encoding=utf8
set ffs=unix,dos,mac
set number
set mouse=c
set clipboard=unnamedplus
set cursorline
set lazyredraw
set showmatch
set mat=2
set sw=0
syntax enable

" A buffer becomes hidden when it is abandoned
set hid

" number of lines to keep above and below the cursor
:set scrolloff=15

" Configure backspace
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Search
set ignorecase
set smartcase
set hlsearch
set incsearch

" Theme
colorscheme codedark
set background=dark

" No backups
set nobackup
set nowb
set noswapfile

" Tabs
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

" Search
map <space> /
map <c-space> ?

" Move between splits
set splitbelow splitright

" Remap splits
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" adjust split sizes
noremap <silent> <C-Left> :vertical resize +3<CR>
noremap <silent> <C-Right> :vertical resize -3<CR>
noremap <silent> <C-Up> :resize +3<CR>
noremap <silent> <C-Down> :resize -3<CR>

" Change 2 split windows from vert to horizontal or other way around
map th <C-w>t<C-w>H
map tk <C-w>t<C-w>K

" Switch buffers
map <leader>bl :bnext<cr>
map <leader>bh :bprevious<cr>

" Map window tabs
map tn :tabnew<cr>
map tc :tabclose<cr>
map tm :tabmove
execute "set <M-l>=\el"
execute "set <M-h>=\eh"
noremap <M-l> :tabnext<cr>
noremap <M-h> :tabprev<cr>

" Hide menu bar, toolbar and scrollbar in gui
set guioptions-=m  "menu bar
set guioptions-=T  "toolbar
set guioptions-=r  "scrollbar
set guioptions-=l "scrollbar
set guioptions-=L "scrollbar

" File extensions
au BufRead,BufNewFile *.launch set filetype=xml
au BufRead,BufNewFile *.test set filetype=xml
au BufRead,BufNewFile *.test.in set filetype=xml
au BufRead,BufNewFile *.dxy set syntax=cpp.doxygen
au BufRead,BufNewFile *.conf set syntax=dosini
au BufRead,BufNewFile Jenkinsfile set syntax=groovy

"Remove all trailing whitespace by pressing F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" ####################################   PLUGINS SETTINGS   #######################################

" ===== FZF and rg
set rtp+=~/.fzf
nnoremap <C-f> :Files<Cr>
nnoremap <C-g> :Rg<Cr>
let g:fzf_buffers_jump = 1 " [Buffers] Jump to the existing window if possible

" ===== NERDTree
map <leader>n :NERDTreeToggle<cr>
map <leader>r :NERDTreeFind<cr>
let g:NERDTreeWinSize=30
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
