" VUNDLE
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plugins
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'vim-airline/vim-airline'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-obsession'
Plugin 'dhruvasagar/vim-prosession'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'godlygeek/tabular'
Plugin 'rhysd/vim-clang-format'
Plugin 'junegunn/fzf.vim'
Plugin 'dense-analysis/ale'
Plugin 'cespare/vim-toml'
Plugin 'vim-python/python-syntax'
"Plugin 'ycm-core/YouCompleteMe'
Plugin 'davidhalter/jedi-vim'

call vundle#end()

" GENERAL
let mapleader = ","
let maplocalleader = ",,"

filetype plugin indent on
set history=500
set omnifunc=syntaxcomplete#Complete
set autoread
set wildmenu
set ruler
set cmdheight=2
set encoding=utf8
set ffs=unix,dos,mac
set number
set mouse=c
set clipboard=unnamedplus
set cursorline
set lazyredraw
set showmatch
set mat=2

" A buffer becomes hidden when it is abandoned
set hid

" Configure backspace
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Search
set ignorecase
set smartcase
set hlsearch
set incsearch

syntax enable

" enable all Python syntax highlighting features
let python_highlight_all = 1
let python_version_2 = 0

" Theme
colorscheme PaperColor
set background=dark

" No backups
set nobackup
set nowb
set noswapfile

" Tabs
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

set sw=0

" Folding
set foldenable
set foldlevelstart=0
set foldnestmax=10
map <leader>z za

map <space> /
map <c-space> ?

" Move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Switch buffers
map <leader>bl :bnext<cr>
map <leader>bh :bprevious<cr>

" Map tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>tl :tabnext<cr>
map <leader>th :tabprev<cr>

" Start gvim in full screen
if has('gui_running')
    set guifont=Monospace\ 13
    set lines=999 columns=999
endif

" Hide men bar, toolbar and scrollbar
set guioptions-=m  "menu bar
set guioptions-=T  "toolbar
set guioptions-=r  "scrollbar
set guioptions-=l "scrollbar
set guioptions-=L "scrollbar

" FZF
set rtp+=~/.fzf

nnoremap <C-f> :Files<Cr>
nnoremap <C-g> :Rg<Cr>

" [Buffers] Jump to the existing window if possible
let g:fzf_buffers_jump = 1
" [Tags] Command to generate tags file
let g:fzf_tags_command = 'ctags -R'

" Map Nerdtree
map <leader>n :NERDTreeToggle<cr>
map <leader>r :NERDTreeFind<cr>

" Custom file extensions
au BufRead,BufNewFile *.launch set filetype=xml
au BufRead,BufNewFile *.test set filetype=xml
au BufRead,BufNewFile *.test.in set filetype=xml
au BufRead,BufNewFile *.dxy set syntax=cpp.doxygen

" edit vimrc/zshrc and load vimrc bindings
nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>ez :vsp ~/.zshrc<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

" Clear whitespace on save
"autocmd BufWritePre * %s/\s\+$//e

" Tags
" Look for a tag file in the directory of the current file, upwards until
" reaching HOME
set tags=./tags,tags;$HOME

" Ctrl-[ to open tag in a new tab
map <C-W><C-[> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>
" Ctrl-] to open tag in a vertical split
map <C-W><C-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

" Termdebug
let g:termdebug_wide = 1
packadd termdebug

" Python
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

" Jedi-vim
let g:jedi#completions_command = "<Tab>"
let g:jedi#usages_command = "<leader>u"

" YCM
"let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/.ycm_extra_conf.py"
