# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="~/.oh-my-zsh"
ZSH_THEME="powerlevel9k/powerlevel9k"
DISABLE_AUTO_TITLE="false"

# PLUGINS
plugins=(globalias git docker mvn pip python sudo tmux)

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ALIASES
unalias -m '*'
alias ws="cd ~/workspace"
alias dotf="cd ~/workspace/git/dotfiles"
alias ll='ls -alF'
alias l='ls -lF'

export LESS="-XR"

################### POWERLEVEL9K SETTINGS ###################

# General Prompt settings
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ip date time)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

# Context Settings
DEFAULT_USER=krasimir
POWERLEVEL9K_ALWAYS_SHOW_USER=true
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true

# COLOR CUSTOMIZATION

# List all available colors
# for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"

# Context
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='033' #light blue
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='red'
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND='red'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='082' #green
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND='082' #green

# Dir
POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_BACKGROUND='082'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='087' #ligth blue
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='196' #red
POWERLEVEL9K_DIR_ETC_FOREGROUND='black'
POWERLEVEL9K_DIR_ETC_BACKGROUND='196' #red

# VCS
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='010' #green
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='011' #yellow
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='196' #red

# IP
POWERLEVEL9K_IP_FOREGROUND='white'
POWERLEVEL9K_IP_BACKGROUND='234'

# DATE
POWERLEVEL9K_DATE_FOREGROUND='white'
POWERLEVEL9K_DATE_BACKGROUND='237'

# TIME
POWERLEVEL9K_TIME_FOREGROUND='black'
POWERLEVEL9K_TIME_BACKGROUND='247'
