# GENERAL
export TERM="xterm-256color"
export ZSH="/home/$USER/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_TITLE="true"

# PLUGINS
plugins=(globalias git docker docker-compose pip python rust sudo tmux zsh-syntax-highlighting zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

# ALIASES
unalias -m '*'
alias grep="grep --color=auto"
alias ipa="ip -c a"
alias ws="cd ~/workspace"
alias ls='ls --color=auto'
alias ll='ls -alF'
alias l='ls -lF'
alias c='clear'
alias o='xdg-open'
alias gitupd='gitup -t -1 -p'

# HUNTER
alias hunter_build='build.py --jobs=8 --toolchain=gcc-7-cxx14-pic \
--fwd HUNTER_RUN_INSTALL=ON HUNTER_CONFIGURATION_TYPES=Release \
--config Release '

alias hunter_build_debug='build.py --jobs=8 --toolchain=gcc-7-cxx14-pic \
--fwd HUNTER_RUN_INSTALL=ON HUNTER_CONFIGURATION_TYPES=Debug HUNTER_KEEP_PACKAGE_SOURCES=ON \
--config Debug '

source ~/workspace/git/kgeorgiev93/hunter-docker-builds/.bash_aliases

# BINDS
bindkey '^ ' autosuggest-accept # binds ctrl-space to accept current autosuggestion

# EXPORTS
export LESS="-XRF"
export PATH=~/workspace/git/ruslo/polly/bin:~/.cargo/bin:~/.local/bin:$PATH
export FZF_DEFAULT_COMMAND='rg --files --ignore-vcs --hidden'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
